
package br.jus.cnj.pje;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.wsaddressing.W3CEndpointReferenceBuilder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "IntercomunicacaoService", targetNamespace = "http://www.cnj.jus.br/servico-intercomunicacao-2.1/", wsdlLocation = "/META-INF/intercomunicacao.wsdl")
public class IntercomunicacaoService
    extends Service
{

    private final static URL INTERCOMUNICACAOSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.jus.cnj.pje.IntercomunicacaoService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.jus.cnj.pje.IntercomunicacaoService.class.getResource(".");
            url = new URL(baseUrl, "http://pje.trt13.jus.br/primeirograu/intercomunicacao?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://pje.trt13.jus.br/primeirograu/intercomunicacao?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        INTERCOMUNICACAOSERVICE_WSDL_LOCATION = url;
    }

    public IntercomunicacaoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IntercomunicacaoService() {
        super(INTERCOMUNICACAOSERVICE_WSDL_LOCATION, new QName("http://www.cnj.jus.br/servico-intercomunicacao-2.1/", "IntercomunicacaoService"));
    }
    
    public IntercomunicacaoService(URL wsdlLocation) {
        super(wsdlLocation, new QName("http://www.cnj.jus.br/servico-intercomunicacao-2.1/", "IntercomunicacaoService"));
    }

    /**
     * 
     * @return
     *     returns ServicoIntercomunicacao21
     */
    @WebEndpoint(name = "IntercomunicacaoImplPort")
    public ServicoIntercomunicacao21 getIntercomunicacaoImplPort(String address) {
    	W3CEndpointReferenceBuilder b = new W3CEndpointReferenceBuilder();
    	b.address(address)
    		.serviceName(new QName("http://www.cnj.jus.br/servico-intercomunicacao-2.1/", "IntercomunicacaoService"))
    		.endpointName(new QName("http://www.cnj.jus.br/servico-intercomunicacao-2.1/", "IntercomunicacaoImplPort"));
        return super.getPort(b.build(), ServicoIntercomunicacao21.class,(WebServiceFeature[]) null);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicoIntercomunicacao21
     */
    @WebEndpoint(name = "IntercomunicacaoImplPort")
    public ServicoIntercomunicacao21 getIntercomunicacaoImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.cnj.jus.br/servico-intercomunicacao-2.1/", "IntercomunicacaoImplPort"), ServicoIntercomunicacao21.class, features);
    }

}
