/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-06-26 16:27:34 UTC)
 * on 2013-07-15 at 15:04:29 UTC 
 * Modify at your own risk.
 */

package com.ctm.eadvogado.endpoints.processoEndpoint;

/**
 * Service definition for ProcessoEndpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ProcessoEndpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class ProcessoEndpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.15.0-rc of the  library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://e-advogado-web.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "processoEndpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public ProcessoEndpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  ProcessoEndpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "associarProcessoAoUsuario".
   *
   * This request holds the parameters needed by the the processoEndpoint server.  After setting any
   * optional parameters, call the {@link AssociarProcessoAoUsuario#execute()} method to invoke the
   * remote operation.
   *
   * @param email
   * @param idProcesso
   * @return the request
   */
  public AssociarProcessoAoUsuario associarProcessoAoUsuario(java.lang.String email, java.lang.Long idProcesso) throws java.io.IOException {
    AssociarProcessoAoUsuario result = new AssociarProcessoAoUsuario(email, idProcesso);
    initialize(result);
    return result;
  }

  public class AssociarProcessoAoUsuario extends ProcessoEndpointRequest<Void> {

    private static final String REST_PATH = "associarProcessoAoUsuario/{email}/{idProcesso}";

    /**
     * Create a request for the method "associarProcessoAoUsuario".
     *
     * This request holds the parameters needed by the the processoEndpoint server.  After setting any
     * optional parameters, call the {@link AssociarProcessoAoUsuario#execute()} method to invoke the
     * remote operation. <p> {@link AssociarProcessoAoUsuario#initialize(com.google.api.client.googlea
     * pis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param email
     * @param idProcesso
     * @since 1.13
     */
    protected AssociarProcessoAoUsuario(java.lang.String email, java.lang.Long idProcesso) {
      super(ProcessoEndpoint.this, "POST", REST_PATH, null, Void.class);
      this.email = com.google.api.client.util.Preconditions.checkNotNull(email, "Required parameter email must be specified.");
      this.idProcesso = com.google.api.client.util.Preconditions.checkNotNull(idProcesso, "Required parameter idProcesso must be specified.");
    }

    @Override
    public AssociarProcessoAoUsuario setAlt(java.lang.String alt) {
      return (AssociarProcessoAoUsuario) super.setAlt(alt);
    }

    @Override
    public AssociarProcessoAoUsuario setFields(java.lang.String fields) {
      return (AssociarProcessoAoUsuario) super.setFields(fields);
    }

    @Override
    public AssociarProcessoAoUsuario setKey(java.lang.String key) {
      return (AssociarProcessoAoUsuario) super.setKey(key);
    }

    @Override
    public AssociarProcessoAoUsuario setOauthToken(java.lang.String oauthToken) {
      return (AssociarProcessoAoUsuario) super.setOauthToken(oauthToken);
    }

    @Override
    public AssociarProcessoAoUsuario setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (AssociarProcessoAoUsuario) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public AssociarProcessoAoUsuario setQuotaUser(java.lang.String quotaUser) {
      return (AssociarProcessoAoUsuario) super.setQuotaUser(quotaUser);
    }

    @Override
    public AssociarProcessoAoUsuario setUserIp(java.lang.String userIp) {
      return (AssociarProcessoAoUsuario) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String email;

    /**

     */
    public java.lang.String getEmail() {
      return email;
    }

    public AssociarProcessoAoUsuario setEmail(java.lang.String email) {
      this.email = email;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Long idProcesso;

    /**

     */
    public java.lang.Long getIdProcesso() {
      return idProcesso;
    }

    public AssociarProcessoAoUsuario setIdProcesso(java.lang.Long idProcesso) {
      this.idProcesso = idProcesso;
      return this;
    }

    @Override
    public AssociarProcessoAoUsuario set(String parameterName, Object value) {
      return (AssociarProcessoAoUsuario) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "consultarDocumento".
   *
   * This request holds the parameters needed by the the processoEndpoint server.  After setting any
   * optional parameters, call the {@link ConsultarDocumento#execute()} method to invoke the remote
   * operation.
   *
   * @param npu
   * @param idTribunal
   * @param tipoJuizo
   * @param idDocumento
   * @return the request
   */
  public ConsultarDocumento consultarDocumento(java.lang.String npu, java.lang.Long idTribunal, java.lang.String tipoJuizo, java.lang.String idDocumento) throws java.io.IOException {
    ConsultarDocumento result = new ConsultarDocumento(npu, idTribunal, tipoJuizo, idDocumento);
    initialize(result);
    return result;
  }

  public class ConsultarDocumento extends ProcessoEndpointRequest<com.ctm.eadvogado.endpoints.processoEndpoint.model.Documento> {

    private static final String REST_PATH = "consultarDocumento/{npu}/{idTribunal}/{tipoJuizo}/{idDocumento}";

    /**
     * Create a request for the method "consultarDocumento".
     *
     * This request holds the parameters needed by the the processoEndpoint server.  After setting any
     * optional parameters, call the {@link ConsultarDocumento#execute()} method to invoke the remote
     * operation. <p> {@link ConsultarDocumento#initialize(com.google.api.client.googleapis.services.A
     * bstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param npu
     * @param idTribunal
     * @param tipoJuizo
     * @param idDocumento
     * @since 1.13
     */
    protected ConsultarDocumento(java.lang.String npu, java.lang.Long idTribunal, java.lang.String tipoJuizo, java.lang.String idDocumento) {
      super(ProcessoEndpoint.this, "POST", REST_PATH, null, com.ctm.eadvogado.endpoints.processoEndpoint.model.Documento.class);
      this.npu = com.google.api.client.util.Preconditions.checkNotNull(npu, "Required parameter npu must be specified.");
      this.idTribunal = com.google.api.client.util.Preconditions.checkNotNull(idTribunal, "Required parameter idTribunal must be specified.");
      this.tipoJuizo = com.google.api.client.util.Preconditions.checkNotNull(tipoJuizo, "Required parameter tipoJuizo must be specified.");
      this.idDocumento = com.google.api.client.util.Preconditions.checkNotNull(idDocumento, "Required parameter idDocumento must be specified.");
    }

    @Override
    public ConsultarDocumento setAlt(java.lang.String alt) {
      return (ConsultarDocumento) super.setAlt(alt);
    }

    @Override
    public ConsultarDocumento setFields(java.lang.String fields) {
      return (ConsultarDocumento) super.setFields(fields);
    }

    @Override
    public ConsultarDocumento setKey(java.lang.String key) {
      return (ConsultarDocumento) super.setKey(key);
    }

    @Override
    public ConsultarDocumento setOauthToken(java.lang.String oauthToken) {
      return (ConsultarDocumento) super.setOauthToken(oauthToken);
    }

    @Override
    public ConsultarDocumento setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ConsultarDocumento) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ConsultarDocumento setQuotaUser(java.lang.String quotaUser) {
      return (ConsultarDocumento) super.setQuotaUser(quotaUser);
    }

    @Override
    public ConsultarDocumento setUserIp(java.lang.String userIp) {
      return (ConsultarDocumento) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String npu;

    /**

     */
    public java.lang.String getNpu() {
      return npu;
    }

    public ConsultarDocumento setNpu(java.lang.String npu) {
      this.npu = npu;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Long idTribunal;

    /**

     */
    public java.lang.Long getIdTribunal() {
      return idTribunal;
    }

    public ConsultarDocumento setIdTribunal(java.lang.Long idTribunal) {
      this.idTribunal = idTribunal;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String tipoJuizo;

    /**

     */
    public java.lang.String getTipoJuizo() {
      return tipoJuizo;
    }

    public ConsultarDocumento setTipoJuizo(java.lang.String tipoJuizo) {
      this.tipoJuizo = tipoJuizo;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String idDocumento;

    /**

     */
    public java.lang.String getIdDocumento() {
      return idDocumento;
    }

    public ConsultarDocumento setIdDocumento(java.lang.String idDocumento) {
      this.idDocumento = idDocumento;
      return this;
    }

    @Override
    public ConsultarDocumento set(String parameterName, Object value) {
      return (ConsultarDocumento) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "consultarProcesso".
   *
   * This request holds the parameters needed by the the processoEndpoint server.  After setting any
   * optional parameters, call the {@link ConsultarProcesso#execute()} method to invoke the remote
   * operation.
   *
   * @param npu
   * @param idTribunal
   * @param tipoJuizo
   * @param ignorarCache
   * @return the request
   */
  public ConsultarProcesso consultarProcesso(java.lang.String npu, java.lang.Long idTribunal, java.lang.String tipoJuizo, java.lang.Boolean ignorarCache) throws java.io.IOException {
    ConsultarProcesso result = new ConsultarProcesso(npu, idTribunal, tipoJuizo, ignorarCache);
    initialize(result);
    return result;
  }

  public class ConsultarProcesso extends ProcessoEndpointRequest<com.ctm.eadvogado.endpoints.processoEndpoint.model.Processo> {

    private static final String REST_PATH = "consultarProcesso/{npu}/{idTribunal}/{tipoJuizo}/{ignorarCache}";

    /**
     * Create a request for the method "consultarProcesso".
     *
     * This request holds the parameters needed by the the processoEndpoint server.  After setting any
     * optional parameters, call the {@link ConsultarProcesso#execute()} method to invoke the remote
     * operation. <p> {@link ConsultarProcesso#initialize(com.google.api.client.googleapis.services.Ab
     * stractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param npu
     * @param idTribunal
     * @param tipoJuizo
     * @param ignorarCache
     * @since 1.13
     */
    protected ConsultarProcesso(java.lang.String npu, java.lang.Long idTribunal, java.lang.String tipoJuizo, java.lang.Boolean ignorarCache) {
      super(ProcessoEndpoint.this, "POST", REST_PATH, null, com.ctm.eadvogado.endpoints.processoEndpoint.model.Processo.class);
      this.npu = com.google.api.client.util.Preconditions.checkNotNull(npu, "Required parameter npu must be specified.");
      this.idTribunal = com.google.api.client.util.Preconditions.checkNotNull(idTribunal, "Required parameter idTribunal must be specified.");
      this.tipoJuizo = com.google.api.client.util.Preconditions.checkNotNull(tipoJuizo, "Required parameter tipoJuizo must be specified.");
      this.ignorarCache = com.google.api.client.util.Preconditions.checkNotNull(ignorarCache, "Required parameter ignorarCache must be specified.");
    }

    @Override
    public ConsultarProcesso setAlt(java.lang.String alt) {
      return (ConsultarProcesso) super.setAlt(alt);
    }

    @Override
    public ConsultarProcesso setFields(java.lang.String fields) {
      return (ConsultarProcesso) super.setFields(fields);
    }

    @Override
    public ConsultarProcesso setKey(java.lang.String key) {
      return (ConsultarProcesso) super.setKey(key);
    }

    @Override
    public ConsultarProcesso setOauthToken(java.lang.String oauthToken) {
      return (ConsultarProcesso) super.setOauthToken(oauthToken);
    }

    @Override
    public ConsultarProcesso setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ConsultarProcesso) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ConsultarProcesso setQuotaUser(java.lang.String quotaUser) {
      return (ConsultarProcesso) super.setQuotaUser(quotaUser);
    }

    @Override
    public ConsultarProcesso setUserIp(java.lang.String userIp) {
      return (ConsultarProcesso) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String npu;

    /**

     */
    public java.lang.String getNpu() {
      return npu;
    }

    public ConsultarProcesso setNpu(java.lang.String npu) {
      this.npu = npu;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Long idTribunal;

    /**

     */
    public java.lang.Long getIdTribunal() {
      return idTribunal;
    }

    public ConsultarProcesso setIdTribunal(java.lang.Long idTribunal) {
      this.idTribunal = idTribunal;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String tipoJuizo;

    /**

     */
    public java.lang.String getTipoJuizo() {
      return tipoJuizo;
    }

    public ConsultarProcesso setTipoJuizo(java.lang.String tipoJuizo) {
      this.tipoJuizo = tipoJuizo;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Boolean ignorarCache;

    /**

     */
    public java.lang.Boolean getIgnorarCache() {
      return ignorarCache;
    }

    public ConsultarProcesso setIgnorarCache(java.lang.Boolean ignorarCache) {
      this.ignorarCache = ignorarCache;
      return this;
    }

    @Override
    public ConsultarProcesso set(String parameterName, Object value) {
      return (ConsultarProcesso) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "consultarProcessosDoUsuario".
   *
   * This request holds the parameters needed by the the processoEndpoint server.  After setting any
   * optional parameters, call the {@link ConsultarProcessosDoUsuario#execute()} method to invoke the
   * remote operation.
   *
   * @param email
   * @param senha
   * @return the request
   */
  public ConsultarProcessosDoUsuario consultarProcessosDoUsuario(java.lang.String email, java.lang.String senha) throws java.io.IOException {
    ConsultarProcessosDoUsuario result = new ConsultarProcessosDoUsuario(email, senha);
    initialize(result);
    return result;
  }

  public class ConsultarProcessosDoUsuario extends ProcessoEndpointRequest<com.ctm.eadvogado.endpoints.processoEndpoint.model.ProcessoUsuarioCollection> {

    private static final String REST_PATH = "consultarProcessosDoUsuario/{email}/{senha}";

    /**
     * Create a request for the method "consultarProcessosDoUsuario".
     *
     * This request holds the parameters needed by the the processoEndpoint server.  After setting any
     * optional parameters, call the {@link ConsultarProcessosDoUsuario#execute()} method to invoke
     * the remote operation. <p> {@link ConsultarProcessosDoUsuario#initialize(com.google.api.client.g
     * oogleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param email
     * @param senha
     * @since 1.13
     */
    protected ConsultarProcessosDoUsuario(java.lang.String email, java.lang.String senha) {
      super(ProcessoEndpoint.this, "POST", REST_PATH, null, com.ctm.eadvogado.endpoints.processoEndpoint.model.ProcessoUsuarioCollection.class);
      this.email = com.google.api.client.util.Preconditions.checkNotNull(email, "Required parameter email must be specified.");
      this.senha = com.google.api.client.util.Preconditions.checkNotNull(senha, "Required parameter senha must be specified.");
    }

    @Override
    public ConsultarProcessosDoUsuario setAlt(java.lang.String alt) {
      return (ConsultarProcessosDoUsuario) super.setAlt(alt);
    }

    @Override
    public ConsultarProcessosDoUsuario setFields(java.lang.String fields) {
      return (ConsultarProcessosDoUsuario) super.setFields(fields);
    }

    @Override
    public ConsultarProcessosDoUsuario setKey(java.lang.String key) {
      return (ConsultarProcessosDoUsuario) super.setKey(key);
    }

    @Override
    public ConsultarProcessosDoUsuario setOauthToken(java.lang.String oauthToken) {
      return (ConsultarProcessosDoUsuario) super.setOauthToken(oauthToken);
    }

    @Override
    public ConsultarProcessosDoUsuario setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ConsultarProcessosDoUsuario) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ConsultarProcessosDoUsuario setQuotaUser(java.lang.String quotaUser) {
      return (ConsultarProcessosDoUsuario) super.setQuotaUser(quotaUser);
    }

    @Override
    public ConsultarProcessosDoUsuario setUserIp(java.lang.String userIp) {
      return (ConsultarProcessosDoUsuario) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String email;

    /**

     */
    public java.lang.String getEmail() {
      return email;
    }

    public ConsultarProcessosDoUsuario setEmail(java.lang.String email) {
      this.email = email;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String senha;

    /**

     */
    public java.lang.String getSenha() {
      return senha;
    }

    public ConsultarProcessosDoUsuario setSenha(java.lang.String senha) {
      this.senha = senha;
      return this;
    }

    @Override
    public ConsultarProcessosDoUsuario set(String parameterName, Object value) {
      return (ConsultarProcessosDoUsuario) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getByID".
   *
   * This request holds the parameters needed by the the processoEndpoint server.  After setting any
   * optional parameters, call the {@link GetByID#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetByID getByID(java.lang.Long id) throws java.io.IOException {
    GetByID result = new GetByID(id);
    initialize(result);
    return result;
  }

  public class GetByID extends ProcessoEndpointRequest<com.ctm.eadvogado.endpoints.processoEndpoint.model.Processo> {

    private static final String REST_PATH = "processo/{id}";

    /**
     * Create a request for the method "getByID".
     *
     * This request holds the parameters needed by the the processoEndpoint server.  After setting any
     * optional parameters, call the {@link GetByID#execute()} method to invoke the remote operation.
     * <p> {@link
     * GetByID#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetByID(java.lang.Long id) {
      super(ProcessoEndpoint.this, "GET", REST_PATH, null, com.ctm.eadvogado.endpoints.processoEndpoint.model.Processo.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetByID setAlt(java.lang.String alt) {
      return (GetByID) super.setAlt(alt);
    }

    @Override
    public GetByID setFields(java.lang.String fields) {
      return (GetByID) super.setFields(fields);
    }

    @Override
    public GetByID setKey(java.lang.String key) {
      return (GetByID) super.setKey(key);
    }

    @Override
    public GetByID setOauthToken(java.lang.String oauthToken) {
      return (GetByID) super.setOauthToken(oauthToken);
    }

    @Override
    public GetByID setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetByID) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetByID setQuotaUser(java.lang.String quotaUser) {
      return (GetByID) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetByID setUserIp(java.lang.String userIp) {
      return (GetByID) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetByID setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetByID set(String parameterName, Object value) {
      return (GetByID) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insert".
   *
   * This request holds the parameters needed by the the processoEndpoint server.  After setting any
   * optional parameters, call the {@link Insert#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.ctm.eadvogado.endpoints.processoEndpoint.model.Processo}
   * @return the request
   */
  public Insert insert(com.ctm.eadvogado.endpoints.processoEndpoint.model.Processo content) throws java.io.IOException {
    Insert result = new Insert(content);
    initialize(result);
    return result;
  }

  public class Insert extends ProcessoEndpointRequest<com.ctm.eadvogado.endpoints.processoEndpoint.model.Processo> {

    private static final String REST_PATH = "processo";

    /**
     * Create a request for the method "insert".
     *
     * This request holds the parameters needed by the the processoEndpoint server.  After setting any
     * optional parameters, call the {@link Insert#execute()} method to invoke the remote operation.
     * <p> {@link
     * Insert#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.ctm.eadvogado.endpoints.processoEndpoint.model.Processo}
     * @since 1.13
     */
    protected Insert(com.ctm.eadvogado.endpoints.processoEndpoint.model.Processo content) {
      super(ProcessoEndpoint.this, "POST", REST_PATH, content, com.ctm.eadvogado.endpoints.processoEndpoint.model.Processo.class);
    }

    @Override
    public Insert setAlt(java.lang.String alt) {
      return (Insert) super.setAlt(alt);
    }

    @Override
    public Insert setFields(java.lang.String fields) {
      return (Insert) super.setFields(fields);
    }

    @Override
    public Insert setKey(java.lang.String key) {
      return (Insert) super.setKey(key);
    }

    @Override
    public Insert setOauthToken(java.lang.String oauthToken) {
      return (Insert) super.setOauthToken(oauthToken);
    }

    @Override
    public Insert setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Insert) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Insert setQuotaUser(java.lang.String quotaUser) {
      return (Insert) super.setQuotaUser(quotaUser);
    }

    @Override
    public Insert setUserIp(java.lang.String userIp) {
      return (Insert) super.setUserIp(userIp);
    }

    @Override
    public Insert set(String parameterName, Object value) {
      return (Insert) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listAll".
   *
   * This request holds the parameters needed by the the processoEndpoint server.  After setting any
   * optional parameters, call the {@link ListAll#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListAll listAll() throws java.io.IOException {
    ListAll result = new ListAll();
    initialize(result);
    return result;
  }

  public class ListAll extends ProcessoEndpointRequest<com.ctm.eadvogado.endpoints.processoEndpoint.model.CollectionResponseProcesso> {

    private static final String REST_PATH = "processo";

    /**
     * Create a request for the method "listAll".
     *
     * This request holds the parameters needed by the the processoEndpoint server.  After setting any
     * optional parameters, call the {@link ListAll#execute()} method to invoke the remote operation.
     * <p> {@link
     * ListAll#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListAll() {
      super(ProcessoEndpoint.this, "GET", REST_PATH, null, com.ctm.eadvogado.endpoints.processoEndpoint.model.CollectionResponseProcesso.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListAll setAlt(java.lang.String alt) {
      return (ListAll) super.setAlt(alt);
    }

    @Override
    public ListAll setFields(java.lang.String fields) {
      return (ListAll) super.setFields(fields);
    }

    @Override
    public ListAll setKey(java.lang.String key) {
      return (ListAll) super.setKey(key);
    }

    @Override
    public ListAll setOauthToken(java.lang.String oauthToken) {
      return (ListAll) super.setOauthToken(oauthToken);
    }

    @Override
    public ListAll setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListAll) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListAll setQuotaUser(java.lang.String quotaUser) {
      return (ListAll) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListAll setUserIp(java.lang.String userIp) {
      return (ListAll) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Integer firstReault;

    /**

     */
    public java.lang.Integer getFirstReault() {
      return firstReault;
    }

    public ListAll setFirstReault(java.lang.Integer firstReault) {
      this.firstReault = firstReault;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String sortField;

    /**

     */
    public java.lang.String getSortField() {
      return sortField;
    }

    public ListAll setSortField(java.lang.String sortField) {
      this.sortField = sortField;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String sortOrder;

    /**

     */
    public java.lang.String getSortOrder() {
      return sortOrder;
    }

    public ListAll setSortOrder(java.lang.String sortOrder) {
      this.sortOrder = sortOrder;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer maxResults;

    /**

     */
    public java.lang.Integer getMaxResults() {
      return maxResults;
    }

    public ListAll setMaxResults(java.lang.Integer maxResults) {
      this.maxResults = maxResults;
      return this;
    }

    @Override
    public ListAll set(String parameterName, Object value) {
      return (ListAll) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "remove".
   *
   * This request holds the parameters needed by the the processoEndpoint server.  After setting any
   * optional parameters, call the {@link Remove#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public Remove remove(java.lang.Long id) throws java.io.IOException {
    Remove result = new Remove(id);
    initialize(result);
    return result;
  }

  public class Remove extends ProcessoEndpointRequest<com.ctm.eadvogado.endpoints.processoEndpoint.model.Processo> {

    private static final String REST_PATH = "remove/{id}";

    /**
     * Create a request for the method "remove".
     *
     * This request holds the parameters needed by the the processoEndpoint server.  After setting any
     * optional parameters, call the {@link Remove#execute()} method to invoke the remote operation.
     * <p> {@link
     * Remove#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected Remove(java.lang.Long id) {
      super(ProcessoEndpoint.this, "DELETE", REST_PATH, null, com.ctm.eadvogado.endpoints.processoEndpoint.model.Processo.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public Remove setAlt(java.lang.String alt) {
      return (Remove) super.setAlt(alt);
    }

    @Override
    public Remove setFields(java.lang.String fields) {
      return (Remove) super.setFields(fields);
    }

    @Override
    public Remove setKey(java.lang.String key) {
      return (Remove) super.setKey(key);
    }

    @Override
    public Remove setOauthToken(java.lang.String oauthToken) {
      return (Remove) super.setOauthToken(oauthToken);
    }

    @Override
    public Remove setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Remove) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Remove setQuotaUser(java.lang.String quotaUser) {
      return (Remove) super.setQuotaUser(quotaUser);
    }

    @Override
    public Remove setUserIp(java.lang.String userIp) {
      return (Remove) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public Remove setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public Remove set(String parameterName, Object value) {
      return (Remove) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removerProcessoDoUsuario".
   *
   * This request holds the parameters needed by the the processoEndpoint server.  After setting any
   * optional parameters, call the {@link RemoverProcessoDoUsuario#execute()} method to invoke the
   * remote operation.
   *
   * @param email
   * @param idProcesso
   * @return the request
   */
  public RemoverProcessoDoUsuario removerProcessoDoUsuario(java.lang.String email, java.lang.Long idProcesso) throws java.io.IOException {
    RemoverProcessoDoUsuario result = new RemoverProcessoDoUsuario(email, idProcesso);
    initialize(result);
    return result;
  }

  public class RemoverProcessoDoUsuario extends ProcessoEndpointRequest<Void> {

    private static final String REST_PATH = "rprocessodousuario/{email}/{idProcesso}";

    /**
     * Create a request for the method "removerProcessoDoUsuario".
     *
     * This request holds the parameters needed by the the processoEndpoint server.  After setting any
     * optional parameters, call the {@link RemoverProcessoDoUsuario#execute()} method to invoke the
     * remote operation. <p> {@link RemoverProcessoDoUsuario#initialize(com.google.api.client.googleap
     * is.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param email
     * @param idProcesso
     * @since 1.13
     */
    protected RemoverProcessoDoUsuario(java.lang.String email, java.lang.Long idProcesso) {
      super(ProcessoEndpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.email = com.google.api.client.util.Preconditions.checkNotNull(email, "Required parameter email must be specified.");
      this.idProcesso = com.google.api.client.util.Preconditions.checkNotNull(idProcesso, "Required parameter idProcesso must be specified.");
    }

    @Override
    public RemoverProcessoDoUsuario setAlt(java.lang.String alt) {
      return (RemoverProcessoDoUsuario) super.setAlt(alt);
    }

    @Override
    public RemoverProcessoDoUsuario setFields(java.lang.String fields) {
      return (RemoverProcessoDoUsuario) super.setFields(fields);
    }

    @Override
    public RemoverProcessoDoUsuario setKey(java.lang.String key) {
      return (RemoverProcessoDoUsuario) super.setKey(key);
    }

    @Override
    public RemoverProcessoDoUsuario setOauthToken(java.lang.String oauthToken) {
      return (RemoverProcessoDoUsuario) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoverProcessoDoUsuario setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoverProcessoDoUsuario) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoverProcessoDoUsuario setQuotaUser(java.lang.String quotaUser) {
      return (RemoverProcessoDoUsuario) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoverProcessoDoUsuario setUserIp(java.lang.String userIp) {
      return (RemoverProcessoDoUsuario) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String email;

    /**

     */
    public java.lang.String getEmail() {
      return email;
    }

    public RemoverProcessoDoUsuario setEmail(java.lang.String email) {
      this.email = email;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Long idProcesso;

    /**

     */
    public java.lang.Long getIdProcesso() {
      return idProcesso;
    }

    public RemoverProcessoDoUsuario setIdProcesso(java.lang.Long idProcesso) {
      this.idProcesso = idProcesso;
      return this;
    }

    @Override
    public RemoverProcessoDoUsuario set(String parameterName, Object value) {
      return (RemoverProcessoDoUsuario) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "update".
   *
   * This request holds the parameters needed by the the processoEndpoint server.  After setting any
   * optional parameters, call the {@link Update#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.ctm.eadvogado.endpoints.processoEndpoint.model.Processo}
   * @return the request
   */
  public Update update(com.ctm.eadvogado.endpoints.processoEndpoint.model.Processo content) throws java.io.IOException {
    Update result = new Update(content);
    initialize(result);
    return result;
  }

  public class Update extends ProcessoEndpointRequest<com.ctm.eadvogado.endpoints.processoEndpoint.model.Processo> {

    private static final String REST_PATH = "processo";

    /**
     * Create a request for the method "update".
     *
     * This request holds the parameters needed by the the processoEndpoint server.  After setting any
     * optional parameters, call the {@link Update#execute()} method to invoke the remote operation.
     * <p> {@link
     * Update#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.ctm.eadvogado.endpoints.processoEndpoint.model.Processo}
     * @since 1.13
     */
    protected Update(com.ctm.eadvogado.endpoints.processoEndpoint.model.Processo content) {
      super(ProcessoEndpoint.this, "PUT", REST_PATH, content, com.ctm.eadvogado.endpoints.processoEndpoint.model.Processo.class);
    }

    @Override
    public Update setAlt(java.lang.String alt) {
      return (Update) super.setAlt(alt);
    }

    @Override
    public Update setFields(java.lang.String fields) {
      return (Update) super.setFields(fields);
    }

    @Override
    public Update setKey(java.lang.String key) {
      return (Update) super.setKey(key);
    }

    @Override
    public Update setOauthToken(java.lang.String oauthToken) {
      return (Update) super.setOauthToken(oauthToken);
    }

    @Override
    public Update setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Update) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Update setQuotaUser(java.lang.String quotaUser) {
      return (Update) super.setQuotaUser(quotaUser);
    }

    @Override
    public Update setUserIp(java.lang.String userIp) {
      return (Update) super.setUserIp(userIp);
    }

    @Override
    public Update set(String parameterName, Object value) {
      return (Update) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link ProcessoEndpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link ProcessoEndpoint}. */
    @Override
    public ProcessoEndpoint build() {
      return new ProcessoEndpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ProcessoEndpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setProcessoEndpointRequestInitializer(
        ProcessoEndpointRequestInitializer processoendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(processoendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
