/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-06-26 16:27:34 UTC)
 * on 2013-07-12 at 20:27:19 UTC 
 * Modify at your own risk.
 */

package com.ctm.eadvogado.endpoints.lancamentoEndpoint.model;

/**
 * Model definition for Lancamento.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Lancamento extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime data;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key key;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String orderId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer quantidade;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String sku;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String tipo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key usuario;

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getData() {
    return data;
  }

  /**
   * @param data data or {@code null} for none
   */
  public Lancamento setData(com.google.api.client.util.DateTime data) {
    this.data = data;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getKey() {
    return key;
  }

  /**
   * @param key key or {@code null} for none
   */
  public Lancamento setKey(Key key) {
    this.key = key;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getOrderId() {
    return orderId;
  }

  /**
   * @param orderId orderId or {@code null} for none
   */
  public Lancamento setOrderId(java.lang.String orderId) {
    this.orderId = orderId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getQuantidade() {
    return quantidade;
  }

  /**
   * @param quantidade quantidade or {@code null} for none
   */
  public Lancamento setQuantidade(java.lang.Integer quantidade) {
    this.quantidade = quantidade;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSku() {
    return sku;
  }

  /**
   * @param sku sku or {@code null} for none
   */
  public Lancamento setSku(java.lang.String sku) {
    this.sku = sku;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTipo() {
    return tipo;
  }

  /**
   * @param tipo tipo or {@code null} for none
   */
  public Lancamento setTipo(java.lang.String tipo) {
    this.tipo = tipo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getUsuario() {
    return usuario;
  }

  /**
   * @param usuario usuario or {@code null} for none
   */
  public Lancamento setUsuario(Key usuario) {
    this.usuario = usuario;
    return this;
  }

  @Override
  public Lancamento set(String fieldName, Object value) {
    return (Lancamento) super.set(fieldName, value);
  }

  @Override
  public Lancamento clone() {
    return (Lancamento) super.clone();
  }

}
