
package br.jus.cnj.pje.consulta.v1;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConsultaPJe", targetNamespace = "http://ws.pje.cnj.jus.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConsultaPJe {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<br.jus.cnj.pje.consulta.v1.AssuntoJudicial>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarAssuntosJudiciais", targetNamespace = "http://ws.pje.cnj.jus.br/", className = "br.jus.cnj.pje.consulta.v1.ConsultarAssuntosJudiciais")
    @ResponseWrapper(localName = "consultarAssuntosJudiciaisResponse", targetNamespace = "http://ws.pje.cnj.jus.br/", className = "br.jus.cnj.pje.consulta.v1.ConsultarAssuntosJudiciaisResponse")
    public List<AssuntoJudicial> consultarAssuntosJudiciais(
        @WebParam(name = "arg0", targetNamespace = "")
        Jurisdicao arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        ClasseJudicial arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<br.jus.cnj.pje.consulta.v1.ClasseJudicial>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarClassesJudiciais", targetNamespace = "http://ws.pje.cnj.jus.br/", className = "br.jus.cnj.pje.consulta.v1.ConsultarClassesJudiciais")
    @ResponseWrapper(localName = "consultarClassesJudiciaisResponse", targetNamespace = "http://ws.pje.cnj.jus.br/", className = "br.jus.cnj.pje.consulta.v1.ConsultarClassesJudiciaisResponse")
    public List<ClasseJudicial> consultarClassesJudiciais(
        @WebParam(name = "arg0", targetNamespace = "")
        Jurisdicao arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<br.jus.cnj.pje.consulta.v1.Competencia>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarCompetencias", targetNamespace = "http://ws.pje.cnj.jus.br/", className = "br.jus.cnj.pje.consulta.v1.ConsultarCompetencias")
    @ResponseWrapper(localName = "consultarCompetenciasResponse", targetNamespace = "http://ws.pje.cnj.jus.br/", className = "br.jus.cnj.pje.consulta.v1.ConsultarCompetenciasResponse")
    public List<Competencia> consultarCompetencias(
        @WebParam(name = "arg0", targetNamespace = "")
        Jurisdicao arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        ClasseJudicial arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        List<AssuntoJudicial> arg2);

    /**
     * 
     * @return
     *     returns java.util.List<br.jus.cnj.pje.consulta.v1.Jurisdicao>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarJurisdicoes", targetNamespace = "http://ws.pje.cnj.jus.br/", className = "br.jus.cnj.pje.consulta.v1.ConsultarJurisdicoes")
    @ResponseWrapper(localName = "consultarJurisdicoesResponse", targetNamespace = "http://ws.pje.cnj.jus.br/", className = "br.jus.cnj.pje.consulta.v1.ConsultarJurisdicoesResponse")
    public List<Jurisdicao> consultarJurisdicoes();

    /**
     * 
     * @return
     *     returns java.util.List<br.jus.cnj.pje.consulta.v1.OrgaoJulgador>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarOrgaosJulgadores", targetNamespace = "http://ws.pje.cnj.jus.br/", className = "br.jus.cnj.pje.consulta.v1.ConsultarOrgaosJulgadores")
    @ResponseWrapper(localName = "consultarOrgaosJulgadoresResponse", targetNamespace = "http://ws.pje.cnj.jus.br/", className = "br.jus.cnj.pje.consulta.v1.ConsultarOrgaosJulgadoresResponse")
    public List<OrgaoJulgador> consultarOrgaosJulgadores();

    /**
     * 
     * @return
     *     returns java.util.List<br.jus.cnj.pje.consulta.v1.OrgaoJulgadorColegiado>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarOrgaosJulgadoresColegiados", targetNamespace = "http://ws.pje.cnj.jus.br/", className = "br.jus.cnj.pje.consulta.v1.ConsultarOrgaosJulgadoresColegiados")
    @ResponseWrapper(localName = "consultarOrgaosJulgadoresColegiadosResponse", targetNamespace = "http://ws.pje.cnj.jus.br/", className = "br.jus.cnj.pje.consulta.v1.ConsultarOrgaosJulgadoresColegiadosResponse")
    public List<OrgaoJulgadorColegiado> consultarOrgaosJulgadoresColegiados();

    /**
     * 
     * @param orgaoJulgador
     * @return
     *     returns java.util.List<br.jus.cnj.pje.consulta.v1.SalaAudiencia>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarSalasAudiencia", targetNamespace = "http://ws.pje.cnj.jus.br/", className = "br.jus.cnj.pje.consulta.v1.ConsultarSalasAudienciaOrgaoJulgador")
    @ResponseWrapper(localName = "consultarSalasAudienciaResponse", targetNamespace = "http://ws.pje.cnj.jus.br/", className = "br.jus.cnj.pje.consulta.v1.ConsultarSalasAudienciaOrgaoJulgadorResponse")
    public List<SalaAudiencia> consultarSalasAudiencia(
        @WebParam(name = "orgaoJulgador", targetNamespace = "")
        OrgaoJulgador orgaoJulgador);

    /**
     * 
     * @return
     *     returns java.util.List<br.jus.cnj.pje.consulta.v1.TipoAudiencia>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarTiposAudiencia", targetNamespace = "http://ws.pje.cnj.jus.br/", className = "br.jus.cnj.pje.consulta.v1.ConsultarTiposAudiencia")
    @ResponseWrapper(localName = "consultarTiposAudienciaResponse", targetNamespace = "http://ws.pje.cnj.jus.br/", className = "br.jus.cnj.pje.consulta.v1.ConsultarTiposAudienciaResponse")
    public List<TipoAudiencia> consultarTiposAudiencia();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<br.jus.cnj.pje.consulta.v1.TipoDocumentoProcessual>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarTiposDocumentoProcessual", targetNamespace = "http://ws.pje.cnj.jus.br/", className = "br.jus.cnj.pje.consulta.v1.ConsultarTiposDocumentoProcessual")
    @ResponseWrapper(localName = "consultarTiposDocumentoProcessualResponse", targetNamespace = "http://ws.pje.cnj.jus.br/", className = "br.jus.cnj.pje.consulta.v1.ConsultarTiposDocumentoProcessualResponse")
    public List<TipoDocumentoProcessual> consultarTiposDocumentoProcessual(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns br.jus.cnj.pje.consulta.v1.Fluxo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recuperarInformacoesFluxo", targetNamespace = "http://ws.pje.cnj.jus.br/", className = "br.jus.cnj.pje.consulta.v1.RecuperarInformacoesFluxo")
    @ResponseWrapper(localName = "recuperarInformacoesFluxoResponse", targetNamespace = "http://ws.pje.cnj.jus.br/", className = "br.jus.cnj.pje.consulta.v1.RecuperarInformacoesFluxoResponse")
    public Fluxo recuperarInformacoesFluxo(
        @WebParam(name = "arg0", targetNamespace = "")
        ClasseJudicial arg0);

}
