/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-08-07 19:00:49 UTC)
 * on 2013-08-09 at 02:52:46 UTC 
 * Modify at your own risk.
 */

package com.ctm.eadvogado.endpoints.usuarioEndpoint;

/**
 * Service definition for UsuarioEndpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link UsuarioEndpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class UsuarioEndpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.15.0-rc of the  library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://e-advogado-web.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "usuarioEndpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public UsuarioEndpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  UsuarioEndpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "autenticar".
   *
   * This request holds the parameters needed by the the usuarioEndpoint server.  After setting any
   * optional parameters, call the {@link Autenticar#execute()} method to invoke the remote operation.
   *
   * @param email
   * @param senha
   * @return the request
   */
  public Autenticar autenticar(java.lang.String email, java.lang.String senha) throws java.io.IOException {
    Autenticar result = new Autenticar(email, senha);
    initialize(result);
    return result;
  }

  public class Autenticar extends UsuarioEndpointRequest<com.ctm.eadvogado.endpoints.usuarioEndpoint.model.Usuario> {

    private static final String REST_PATH = "autenticar/{email}/{senha}";

    /**
     * Create a request for the method "autenticar".
     *
     * This request holds the parameters needed by the the usuarioEndpoint server.  After setting any
     * optional parameters, call the {@link Autenticar#execute()} method to invoke the remote
     * operation. <p> {@link
     * Autenticar#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param email
     * @param senha
     * @since 1.13
     */
    protected Autenticar(java.lang.String email, java.lang.String senha) {
      super(UsuarioEndpoint.this, "POST", REST_PATH, null, com.ctm.eadvogado.endpoints.usuarioEndpoint.model.Usuario.class);
      this.email = com.google.api.client.util.Preconditions.checkNotNull(email, "Required parameter email must be specified.");
      this.senha = com.google.api.client.util.Preconditions.checkNotNull(senha, "Required parameter senha must be specified.");
    }

    @Override
    public Autenticar setAlt(java.lang.String alt) {
      return (Autenticar) super.setAlt(alt);
    }

    @Override
    public Autenticar setFields(java.lang.String fields) {
      return (Autenticar) super.setFields(fields);
    }

    @Override
    public Autenticar setKey(java.lang.String key) {
      return (Autenticar) super.setKey(key);
    }

    @Override
    public Autenticar setOauthToken(java.lang.String oauthToken) {
      return (Autenticar) super.setOauthToken(oauthToken);
    }

    @Override
    public Autenticar setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Autenticar) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Autenticar setQuotaUser(java.lang.String quotaUser) {
      return (Autenticar) super.setQuotaUser(quotaUser);
    }

    @Override
    public Autenticar setUserIp(java.lang.String userIp) {
      return (Autenticar) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String email;

    /**

     */
    public java.lang.String getEmail() {
      return email;
    }

    public Autenticar setEmail(java.lang.String email) {
      this.email = email;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String senha;

    /**

     */
    public java.lang.String getSenha() {
      return senha;
    }

    public Autenticar setSenha(java.lang.String senha) {
      this.senha = senha;
      return this;
    }

    @Override
    public Autenticar set(String parameterName, Object value) {
      return (Autenticar) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "enviarEmailParaTodosUsuarios".
   *
   * This request holds the parameters needed by the the usuarioEndpoint server.  After setting any
   * optional parameters, call the {@link EnviarEmailParaTodosUsuarios#execute()} method to invoke the
   * remote operation.
   *
   * @param assunto
   * @param textContent
   * @param htmlContent
   * @return the request
   */
  public EnviarEmailParaTodosUsuarios enviarEmailParaTodosUsuarios(java.lang.String assunto, java.lang.String textContent, java.lang.String htmlContent) throws java.io.IOException {
    EnviarEmailParaTodosUsuarios result = new EnviarEmailParaTodosUsuarios(assunto, textContent, htmlContent);
    initialize(result);
    return result;
  }

  public class EnviarEmailParaTodosUsuarios extends UsuarioEndpointRequest<Void> {

    private static final String REST_PATH = "enviarEmailParaTodosUsuarios/{assunto}/{textContent}/{htmlContent}";

    /**
     * Create a request for the method "enviarEmailParaTodosUsuarios".
     *
     * This request holds the parameters needed by the the usuarioEndpoint server.  After setting any
     * optional parameters, call the {@link EnviarEmailParaTodosUsuarios#execute()} method to invoke
     * the remote operation. <p> {@link EnviarEmailParaTodosUsuarios#initialize(com.google.api.client.
     * googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param assunto
     * @param textContent
     * @param htmlContent
     * @since 1.13
     */
    protected EnviarEmailParaTodosUsuarios(java.lang.String assunto, java.lang.String textContent, java.lang.String htmlContent) {
      super(UsuarioEndpoint.this, "POST", REST_PATH, null, Void.class);
      this.assunto = com.google.api.client.util.Preconditions.checkNotNull(assunto, "Required parameter assunto must be specified.");
      this.textContent = com.google.api.client.util.Preconditions.checkNotNull(textContent, "Required parameter textContent must be specified.");
      this.htmlContent = com.google.api.client.util.Preconditions.checkNotNull(htmlContent, "Required parameter htmlContent must be specified.");
    }

    @Override
    public EnviarEmailParaTodosUsuarios setAlt(java.lang.String alt) {
      return (EnviarEmailParaTodosUsuarios) super.setAlt(alt);
    }

    @Override
    public EnviarEmailParaTodosUsuarios setFields(java.lang.String fields) {
      return (EnviarEmailParaTodosUsuarios) super.setFields(fields);
    }

    @Override
    public EnviarEmailParaTodosUsuarios setKey(java.lang.String key) {
      return (EnviarEmailParaTodosUsuarios) super.setKey(key);
    }

    @Override
    public EnviarEmailParaTodosUsuarios setOauthToken(java.lang.String oauthToken) {
      return (EnviarEmailParaTodosUsuarios) super.setOauthToken(oauthToken);
    }

    @Override
    public EnviarEmailParaTodosUsuarios setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (EnviarEmailParaTodosUsuarios) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public EnviarEmailParaTodosUsuarios setQuotaUser(java.lang.String quotaUser) {
      return (EnviarEmailParaTodosUsuarios) super.setQuotaUser(quotaUser);
    }

    @Override
    public EnviarEmailParaTodosUsuarios setUserIp(java.lang.String userIp) {
      return (EnviarEmailParaTodosUsuarios) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String assunto;

    /**

     */
    public java.lang.String getAssunto() {
      return assunto;
    }

    public EnviarEmailParaTodosUsuarios setAssunto(java.lang.String assunto) {
      this.assunto = assunto;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String textContent;

    /**

     */
    public java.lang.String getTextContent() {
      return textContent;
    }

    public EnviarEmailParaTodosUsuarios setTextContent(java.lang.String textContent) {
      this.textContent = textContent;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String htmlContent;

    /**

     */
    public java.lang.String getHtmlContent() {
      return htmlContent;
    }

    public EnviarEmailParaTodosUsuarios setHtmlContent(java.lang.String htmlContent) {
      this.htmlContent = htmlContent;
      return this;
    }

    @Override
    public EnviarEmailParaTodosUsuarios set(String parameterName, Object value) {
      return (EnviarEmailParaTodosUsuarios) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "enviarEmailParaUsuario".
   *
   * This request holds the parameters needed by the the usuarioEndpoint server.  After setting any
   * optional parameters, call the {@link EnviarEmailParaUsuario#execute()} method to invoke the
   * remote operation.
   *
   * @param assunto
   * @param textContent
   * @param htmlContent
   * @param email
   * @return the request
   */
  public EnviarEmailParaUsuario enviarEmailParaUsuario(java.lang.String assunto, java.lang.String textContent, java.lang.String htmlContent, java.lang.String email) throws java.io.IOException {
    EnviarEmailParaUsuario result = new EnviarEmailParaUsuario(assunto, textContent, htmlContent, email);
    initialize(result);
    return result;
  }

  public class EnviarEmailParaUsuario extends UsuarioEndpointRequest<Void> {

    private static final String REST_PATH = "enviarEmailParaUsuario/{assunto}/{textContent}/{htmlContent}/{email}";

    /**
     * Create a request for the method "enviarEmailParaUsuario".
     *
     * This request holds the parameters needed by the the usuarioEndpoint server.  After setting any
     * optional parameters, call the {@link EnviarEmailParaUsuario#execute()} method to invoke the
     * remote operation. <p> {@link EnviarEmailParaUsuario#initialize(com.google.api.client.googleapis
     * .services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param assunto
     * @param textContent
     * @param htmlContent
     * @param email
     * @since 1.13
     */
    protected EnviarEmailParaUsuario(java.lang.String assunto, java.lang.String textContent, java.lang.String htmlContent, java.lang.String email) {
      super(UsuarioEndpoint.this, "POST", REST_PATH, null, Void.class);
      this.assunto = com.google.api.client.util.Preconditions.checkNotNull(assunto, "Required parameter assunto must be specified.");
      this.textContent = com.google.api.client.util.Preconditions.checkNotNull(textContent, "Required parameter textContent must be specified.");
      this.htmlContent = com.google.api.client.util.Preconditions.checkNotNull(htmlContent, "Required parameter htmlContent must be specified.");
      this.email = com.google.api.client.util.Preconditions.checkNotNull(email, "Required parameter email must be specified.");
    }

    @Override
    public EnviarEmailParaUsuario setAlt(java.lang.String alt) {
      return (EnviarEmailParaUsuario) super.setAlt(alt);
    }

    @Override
    public EnviarEmailParaUsuario setFields(java.lang.String fields) {
      return (EnviarEmailParaUsuario) super.setFields(fields);
    }

    @Override
    public EnviarEmailParaUsuario setKey(java.lang.String key) {
      return (EnviarEmailParaUsuario) super.setKey(key);
    }

    @Override
    public EnviarEmailParaUsuario setOauthToken(java.lang.String oauthToken) {
      return (EnviarEmailParaUsuario) super.setOauthToken(oauthToken);
    }

    @Override
    public EnviarEmailParaUsuario setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (EnviarEmailParaUsuario) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public EnviarEmailParaUsuario setQuotaUser(java.lang.String quotaUser) {
      return (EnviarEmailParaUsuario) super.setQuotaUser(quotaUser);
    }

    @Override
    public EnviarEmailParaUsuario setUserIp(java.lang.String userIp) {
      return (EnviarEmailParaUsuario) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String assunto;

    /**

     */
    public java.lang.String getAssunto() {
      return assunto;
    }

    public EnviarEmailParaUsuario setAssunto(java.lang.String assunto) {
      this.assunto = assunto;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String textContent;

    /**

     */
    public java.lang.String getTextContent() {
      return textContent;
    }

    public EnviarEmailParaUsuario setTextContent(java.lang.String textContent) {
      this.textContent = textContent;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String htmlContent;

    /**

     */
    public java.lang.String getHtmlContent() {
      return htmlContent;
    }

    public EnviarEmailParaUsuario setHtmlContent(java.lang.String htmlContent) {
      this.htmlContent = htmlContent;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String email;

    /**

     */
    public java.lang.String getEmail() {
      return email;
    }

    public EnviarEmailParaUsuario setEmail(java.lang.String email) {
      this.email = email;
      return this;
    }

    @Override
    public EnviarEmailParaUsuario set(String parameterName, Object value) {
      return (EnviarEmailParaUsuario) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getByID".
   *
   * This request holds the parameters needed by the the usuarioEndpoint server.  After setting any
   * optional parameters, call the {@link GetByID#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetByID getByID(java.lang.Long id) throws java.io.IOException {
    GetByID result = new GetByID(id);
    initialize(result);
    return result;
  }

  public class GetByID extends UsuarioEndpointRequest<com.ctm.eadvogado.endpoints.usuarioEndpoint.model.Usuario> {

    private static final String REST_PATH = "usuario/{id}";

    /**
     * Create a request for the method "getByID".
     *
     * This request holds the parameters needed by the the usuarioEndpoint server.  After setting any
     * optional parameters, call the {@link GetByID#execute()} method to invoke the remote operation.
     * <p> {@link
     * GetByID#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetByID(java.lang.Long id) {
      super(UsuarioEndpoint.this, "GET", REST_PATH, null, com.ctm.eadvogado.endpoints.usuarioEndpoint.model.Usuario.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetByID setAlt(java.lang.String alt) {
      return (GetByID) super.setAlt(alt);
    }

    @Override
    public GetByID setFields(java.lang.String fields) {
      return (GetByID) super.setFields(fields);
    }

    @Override
    public GetByID setKey(java.lang.String key) {
      return (GetByID) super.setKey(key);
    }

    @Override
    public GetByID setOauthToken(java.lang.String oauthToken) {
      return (GetByID) super.setOauthToken(oauthToken);
    }

    @Override
    public GetByID setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetByID) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetByID setQuotaUser(java.lang.String quotaUser) {
      return (GetByID) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetByID setUserIp(java.lang.String userIp) {
      return (GetByID) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetByID setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetByID set(String parameterName, Object value) {
      return (GetByID) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insert".
   *
   * This request holds the parameters needed by the the usuarioEndpoint server.  After setting any
   * optional parameters, call the {@link Insert#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.ctm.eadvogado.endpoints.usuarioEndpoint.model.Usuario}
   * @return the request
   */
  public Insert insert(com.ctm.eadvogado.endpoints.usuarioEndpoint.model.Usuario content) throws java.io.IOException {
    Insert result = new Insert(content);
    initialize(result);
    return result;
  }

  public class Insert extends UsuarioEndpointRequest<com.ctm.eadvogado.endpoints.usuarioEndpoint.model.Usuario> {

    private static final String REST_PATH = "usuario";

    /**
     * Create a request for the method "insert".
     *
     * This request holds the parameters needed by the the usuarioEndpoint server.  After setting any
     * optional parameters, call the {@link Insert#execute()} method to invoke the remote operation.
     * <p> {@link
     * Insert#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.ctm.eadvogado.endpoints.usuarioEndpoint.model.Usuario}
     * @since 1.13
     */
    protected Insert(com.ctm.eadvogado.endpoints.usuarioEndpoint.model.Usuario content) {
      super(UsuarioEndpoint.this, "POST", REST_PATH, content, com.ctm.eadvogado.endpoints.usuarioEndpoint.model.Usuario.class);
    }

    @Override
    public Insert setAlt(java.lang.String alt) {
      return (Insert) super.setAlt(alt);
    }

    @Override
    public Insert setFields(java.lang.String fields) {
      return (Insert) super.setFields(fields);
    }

    @Override
    public Insert setKey(java.lang.String key) {
      return (Insert) super.setKey(key);
    }

    @Override
    public Insert setOauthToken(java.lang.String oauthToken) {
      return (Insert) super.setOauthToken(oauthToken);
    }

    @Override
    public Insert setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Insert) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Insert setQuotaUser(java.lang.String quotaUser) {
      return (Insert) super.setQuotaUser(quotaUser);
    }

    @Override
    public Insert setUserIp(java.lang.String userIp) {
      return (Insert) super.setUserIp(userIp);
    }

    @Override
    public Insert set(String parameterName, Object value) {
      return (Insert) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listAll".
   *
   * This request holds the parameters needed by the the usuarioEndpoint server.  After setting any
   * optional parameters, call the {@link ListAll#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListAll listAll() throws java.io.IOException {
    ListAll result = new ListAll();
    initialize(result);
    return result;
  }

  public class ListAll extends UsuarioEndpointRequest<com.ctm.eadvogado.endpoints.usuarioEndpoint.model.CollectionResponseUsuario> {

    private static final String REST_PATH = "usuario";

    /**
     * Create a request for the method "listAll".
     *
     * This request holds the parameters needed by the the usuarioEndpoint server.  After setting any
     * optional parameters, call the {@link ListAll#execute()} method to invoke the remote operation.
     * <p> {@link
     * ListAll#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListAll() {
      super(UsuarioEndpoint.this, "GET", REST_PATH, null, com.ctm.eadvogado.endpoints.usuarioEndpoint.model.CollectionResponseUsuario.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListAll setAlt(java.lang.String alt) {
      return (ListAll) super.setAlt(alt);
    }

    @Override
    public ListAll setFields(java.lang.String fields) {
      return (ListAll) super.setFields(fields);
    }

    @Override
    public ListAll setKey(java.lang.String key) {
      return (ListAll) super.setKey(key);
    }

    @Override
    public ListAll setOauthToken(java.lang.String oauthToken) {
      return (ListAll) super.setOauthToken(oauthToken);
    }

    @Override
    public ListAll setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListAll) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListAll setQuotaUser(java.lang.String quotaUser) {
      return (ListAll) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListAll setUserIp(java.lang.String userIp) {
      return (ListAll) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Integer firstReault;

    /**

     */
    public java.lang.Integer getFirstReault() {
      return firstReault;
    }

    public ListAll setFirstReault(java.lang.Integer firstReault) {
      this.firstReault = firstReault;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String sortField;

    /**

     */
    public java.lang.String getSortField() {
      return sortField;
    }

    public ListAll setSortField(java.lang.String sortField) {
      this.sortField = sortField;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String sortOrder;

    /**

     */
    public java.lang.String getSortOrder() {
      return sortOrder;
    }

    public ListAll setSortOrder(java.lang.String sortOrder) {
      this.sortOrder = sortOrder;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer maxResults;

    /**

     */
    public java.lang.Integer getMaxResults() {
      return maxResults;
    }

    public ListAll setMaxResults(java.lang.Integer maxResults) {
      this.maxResults = maxResults;
      return this;
    }

    @Override
    public ListAll set(String parameterName, Object value) {
      return (ListAll) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "notificarMovimentacaoProcessual".
   *
   * This request holds the parameters needed by the the usuarioEndpoint server.  After setting any
   * optional parameters, call the {@link NotificarMovimentacaoProcessual#execute()} method to invoke
   * the remote operation.
   *
   * @param npu
   * @param idTribunal
   * @param tipoJuizo
   * @return the request
   */
  public NotificarMovimentacaoProcessual notificarMovimentacaoProcessual(java.lang.String npu, java.lang.Long idTribunal, java.lang.String tipoJuizo) throws java.io.IOException {
    NotificarMovimentacaoProcessual result = new NotificarMovimentacaoProcessual(npu, idTribunal, tipoJuizo);
    initialize(result);
    return result;
  }

  public class NotificarMovimentacaoProcessual extends UsuarioEndpointRequest<Void> {

    private static final String REST_PATH = "notificarMovimentacaoProcessual/{npu}/{idTribunal}/{tipoJuizo}";

    /**
     * Create a request for the method "notificarMovimentacaoProcessual".
     *
     * This request holds the parameters needed by the the usuarioEndpoint server.  After setting any
     * optional parameters, call the {@link NotificarMovimentacaoProcessual#execute()} method to
     * invoke the remote operation. <p> {@link NotificarMovimentacaoProcessual#initialize(com.google.a
     * pi.client.googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this
     * instance immediately after invoking the constructor. </p>
     *
     * @param npu
     * @param idTribunal
     * @param tipoJuizo
     * @since 1.13
     */
    protected NotificarMovimentacaoProcessual(java.lang.String npu, java.lang.Long idTribunal, java.lang.String tipoJuizo) {
      super(UsuarioEndpoint.this, "POST", REST_PATH, null, Void.class);
      this.npu = com.google.api.client.util.Preconditions.checkNotNull(npu, "Required parameter npu must be specified.");
      this.idTribunal = com.google.api.client.util.Preconditions.checkNotNull(idTribunal, "Required parameter idTribunal must be specified.");
      this.tipoJuizo = com.google.api.client.util.Preconditions.checkNotNull(tipoJuizo, "Required parameter tipoJuizo must be specified.");
    }

    @Override
    public NotificarMovimentacaoProcessual setAlt(java.lang.String alt) {
      return (NotificarMovimentacaoProcessual) super.setAlt(alt);
    }

    @Override
    public NotificarMovimentacaoProcessual setFields(java.lang.String fields) {
      return (NotificarMovimentacaoProcessual) super.setFields(fields);
    }

    @Override
    public NotificarMovimentacaoProcessual setKey(java.lang.String key) {
      return (NotificarMovimentacaoProcessual) super.setKey(key);
    }

    @Override
    public NotificarMovimentacaoProcessual setOauthToken(java.lang.String oauthToken) {
      return (NotificarMovimentacaoProcessual) super.setOauthToken(oauthToken);
    }

    @Override
    public NotificarMovimentacaoProcessual setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (NotificarMovimentacaoProcessual) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public NotificarMovimentacaoProcessual setQuotaUser(java.lang.String quotaUser) {
      return (NotificarMovimentacaoProcessual) super.setQuotaUser(quotaUser);
    }

    @Override
    public NotificarMovimentacaoProcessual setUserIp(java.lang.String userIp) {
      return (NotificarMovimentacaoProcessual) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String npu;

    /**

     */
    public java.lang.String getNpu() {
      return npu;
    }

    public NotificarMovimentacaoProcessual setNpu(java.lang.String npu) {
      this.npu = npu;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Long idTribunal;

    /**

     */
    public java.lang.Long getIdTribunal() {
      return idTribunal;
    }

    public NotificarMovimentacaoProcessual setIdTribunal(java.lang.Long idTribunal) {
      this.idTribunal = idTribunal;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String tipoJuizo;

    /**

     */
    public java.lang.String getTipoJuizo() {
      return tipoJuizo;
    }

    public NotificarMovimentacaoProcessual setTipoJuizo(java.lang.String tipoJuizo) {
      this.tipoJuizo = tipoJuizo;
      return this;
    }

    @Override
    public NotificarMovimentacaoProcessual set(String parameterName, Object value) {
      return (NotificarMovimentacaoProcessual) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "remove".
   *
   * This request holds the parameters needed by the the usuarioEndpoint server.  After setting any
   * optional parameters, call the {@link Remove#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public Remove remove(java.lang.Long id) throws java.io.IOException {
    Remove result = new Remove(id);
    initialize(result);
    return result;
  }

  public class Remove extends UsuarioEndpointRequest<com.ctm.eadvogado.endpoints.usuarioEndpoint.model.Usuario> {

    private static final String REST_PATH = "remove/{id}";

    /**
     * Create a request for the method "remove".
     *
     * This request holds the parameters needed by the the usuarioEndpoint server.  After setting any
     * optional parameters, call the {@link Remove#execute()} method to invoke the remote operation.
     * <p> {@link
     * Remove#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected Remove(java.lang.Long id) {
      super(UsuarioEndpoint.this, "DELETE", REST_PATH, null, com.ctm.eadvogado.endpoints.usuarioEndpoint.model.Usuario.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public Remove setAlt(java.lang.String alt) {
      return (Remove) super.setAlt(alt);
    }

    @Override
    public Remove setFields(java.lang.String fields) {
      return (Remove) super.setFields(fields);
    }

    @Override
    public Remove setKey(java.lang.String key) {
      return (Remove) super.setKey(key);
    }

    @Override
    public Remove setOauthToken(java.lang.String oauthToken) {
      return (Remove) super.setOauthToken(oauthToken);
    }

    @Override
    public Remove setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Remove) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Remove setQuotaUser(java.lang.String quotaUser) {
      return (Remove) super.setQuotaUser(quotaUser);
    }

    @Override
    public Remove setUserIp(java.lang.String userIp) {
      return (Remove) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public Remove setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public Remove set(String parameterName, Object value) {
      return (Remove) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "update".
   *
   * This request holds the parameters needed by the the usuarioEndpoint server.  After setting any
   * optional parameters, call the {@link Update#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.ctm.eadvogado.endpoints.usuarioEndpoint.model.Usuario}
   * @return the request
   */
  public Update update(com.ctm.eadvogado.endpoints.usuarioEndpoint.model.Usuario content) throws java.io.IOException {
    Update result = new Update(content);
    initialize(result);
    return result;
  }

  public class Update extends UsuarioEndpointRequest<com.ctm.eadvogado.endpoints.usuarioEndpoint.model.Usuario> {

    private static final String REST_PATH = "usuario";

    /**
     * Create a request for the method "update".
     *
     * This request holds the parameters needed by the the usuarioEndpoint server.  After setting any
     * optional parameters, call the {@link Update#execute()} method to invoke the remote operation.
     * <p> {@link
     * Update#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.ctm.eadvogado.endpoints.usuarioEndpoint.model.Usuario}
     * @since 1.13
     */
    protected Update(com.ctm.eadvogado.endpoints.usuarioEndpoint.model.Usuario content) {
      super(UsuarioEndpoint.this, "PUT", REST_PATH, content, com.ctm.eadvogado.endpoints.usuarioEndpoint.model.Usuario.class);
    }

    @Override
    public Update setAlt(java.lang.String alt) {
      return (Update) super.setAlt(alt);
    }

    @Override
    public Update setFields(java.lang.String fields) {
      return (Update) super.setFields(fields);
    }

    @Override
    public Update setKey(java.lang.String key) {
      return (Update) super.setKey(key);
    }

    @Override
    public Update setOauthToken(java.lang.String oauthToken) {
      return (Update) super.setOauthToken(oauthToken);
    }

    @Override
    public Update setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Update) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Update setQuotaUser(java.lang.String quotaUser) {
      return (Update) super.setQuotaUser(quotaUser);
    }

    @Override
    public Update setUserIp(java.lang.String userIp) {
      return (Update) super.setUserIp(userIp);
    }

    @Override
    public Update set(String parameterName, Object value) {
      return (Update) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link UsuarioEndpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link UsuarioEndpoint}. */
    @Override
    public UsuarioEndpoint build() {
      return new UsuarioEndpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link UsuarioEndpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setUsuarioEndpointRequestInitializer(
        UsuarioEndpointRequestInitializer usuarioendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(usuarioendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
