/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-06-26 16:27:34 UTC)
 * on 2013-07-03 at 01:40:03 UTC 
 * Modify at your own risk.
 */

package com.ctm.eadvogado.tribunalendpoint;

/**
 * Service definition for Tribunalendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link TribunalendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Tribunalendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.15.0-rc of the  library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://e-advogado.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "tribunalendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Tribunalendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Tribunalendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getTribunal".
   *
   * This request holds the parameters needed by the the tribunalendpoint server.  After setting any
   * optional parameters, call the {@link GetTribunal#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetTribunal getTribunal(java.lang.Long id) throws java.io.IOException {
    GetTribunal result = new GetTribunal(id);
    initialize(result);
    return result;
  }

  public class GetTribunal extends TribunalendpointRequest<com.ctm.eadvogado.tribunalendpoint.model.Tribunal> {

    private static final String REST_PATH = "tribunal/{id}";

    /**
     * Create a request for the method "getTribunal".
     *
     * This request holds the parameters needed by the the tribunalendpoint server.  After setting any
     * optional parameters, call the {@link GetTribunal#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetTribunal#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetTribunal(java.lang.Long id) {
      super(Tribunalendpoint.this, "GET", REST_PATH, null, com.ctm.eadvogado.tribunalendpoint.model.Tribunal.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetTribunal setAlt(java.lang.String alt) {
      return (GetTribunal) super.setAlt(alt);
    }

    @Override
    public GetTribunal setFields(java.lang.String fields) {
      return (GetTribunal) super.setFields(fields);
    }

    @Override
    public GetTribunal setKey(java.lang.String key) {
      return (GetTribunal) super.setKey(key);
    }

    @Override
    public GetTribunal setOauthToken(java.lang.String oauthToken) {
      return (GetTribunal) super.setOauthToken(oauthToken);
    }

    @Override
    public GetTribunal setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetTribunal) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetTribunal setQuotaUser(java.lang.String quotaUser) {
      return (GetTribunal) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetTribunal setUserIp(java.lang.String userIp) {
      return (GetTribunal) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetTribunal setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetTribunal set(String parameterName, Object value) {
      return (GetTribunal) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertTribunal".
   *
   * This request holds the parameters needed by the the tribunalendpoint server.  After setting any
   * optional parameters, call the {@link InsertTribunal#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.ctm.eadvogado.tribunalendpoint.model.Tribunal}
   * @return the request
   */
  public InsertTribunal insertTribunal(com.ctm.eadvogado.tribunalendpoint.model.Tribunal content) throws java.io.IOException {
    InsertTribunal result = new InsertTribunal(content);
    initialize(result);
    return result;
  }

  public class InsertTribunal extends TribunalendpointRequest<com.ctm.eadvogado.tribunalendpoint.model.Tribunal> {

    private static final String REST_PATH = "tribunal";

    /**
     * Create a request for the method "insertTribunal".
     *
     * This request holds the parameters needed by the the tribunalendpoint server.  After setting any
     * optional parameters, call the {@link InsertTribunal#execute()} method to invoke the remote
     * operation. <p> {@link InsertTribunal#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.ctm.eadvogado.tribunalendpoint.model.Tribunal}
     * @since 1.13
     */
    protected InsertTribunal(com.ctm.eadvogado.tribunalendpoint.model.Tribunal content) {
      super(Tribunalendpoint.this, "POST", REST_PATH, content, com.ctm.eadvogado.tribunalendpoint.model.Tribunal.class);
    }

    @Override
    public InsertTribunal setAlt(java.lang.String alt) {
      return (InsertTribunal) super.setAlt(alt);
    }

    @Override
    public InsertTribunal setFields(java.lang.String fields) {
      return (InsertTribunal) super.setFields(fields);
    }

    @Override
    public InsertTribunal setKey(java.lang.String key) {
      return (InsertTribunal) super.setKey(key);
    }

    @Override
    public InsertTribunal setOauthToken(java.lang.String oauthToken) {
      return (InsertTribunal) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertTribunal setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertTribunal) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertTribunal setQuotaUser(java.lang.String quotaUser) {
      return (InsertTribunal) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertTribunal setUserIp(java.lang.String userIp) {
      return (InsertTribunal) super.setUserIp(userIp);
    }

    @Override
    public InsertTribunal set(String parameterName, Object value) {
      return (InsertTribunal) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listTribunal".
   *
   * This request holds the parameters needed by the the tribunalendpoint server.  After setting any
   * optional parameters, call the {@link ListTribunal#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListTribunal listTribunal() throws java.io.IOException {
    ListTribunal result = new ListTribunal();
    initialize(result);
    return result;
  }

  public class ListTribunal extends TribunalendpointRequest<com.ctm.eadvogado.tribunalendpoint.model.CollectionResponseTribunal> {

    private static final String REST_PATH = "tribunal";

    /**
     * Create a request for the method "listTribunal".
     *
     * This request holds the parameters needed by the the tribunalendpoint server.  After setting any
     * optional parameters, call the {@link ListTribunal#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListTribunal#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListTribunal() {
      super(Tribunalendpoint.this, "GET", REST_PATH, null, com.ctm.eadvogado.tribunalendpoint.model.CollectionResponseTribunal.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListTribunal setAlt(java.lang.String alt) {
      return (ListTribunal) super.setAlt(alt);
    }

    @Override
    public ListTribunal setFields(java.lang.String fields) {
      return (ListTribunal) super.setFields(fields);
    }

    @Override
    public ListTribunal setKey(java.lang.String key) {
      return (ListTribunal) super.setKey(key);
    }

    @Override
    public ListTribunal setOauthToken(java.lang.String oauthToken) {
      return (ListTribunal) super.setOauthToken(oauthToken);
    }

    @Override
    public ListTribunal setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListTribunal) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListTribunal setQuotaUser(java.lang.String quotaUser) {
      return (ListTribunal) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListTribunal setUserIp(java.lang.String userIp) {
      return (ListTribunal) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListTribunal setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListTribunal setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListTribunal set(String parameterName, Object value) {
      return (ListTribunal) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeTribunal".
   *
   * This request holds the parameters needed by the the tribunalendpoint server.  After setting any
   * optional parameters, call the {@link RemoveTribunal#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveTribunal removeTribunal(java.lang.Long id) throws java.io.IOException {
    RemoveTribunal result = new RemoveTribunal(id);
    initialize(result);
    return result;
  }

  public class RemoveTribunal extends TribunalendpointRequest<com.ctm.eadvogado.tribunalendpoint.model.Tribunal> {

    private static final String REST_PATH = "tribunal/{id}";

    /**
     * Create a request for the method "removeTribunal".
     *
     * This request holds the parameters needed by the the tribunalendpoint server.  After setting any
     * optional parameters, call the {@link RemoveTribunal#execute()} method to invoke the remote
     * operation. <p> {@link RemoveTribunal#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveTribunal(java.lang.Long id) {
      super(Tribunalendpoint.this, "DELETE", REST_PATH, null, com.ctm.eadvogado.tribunalendpoint.model.Tribunal.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveTribunal setAlt(java.lang.String alt) {
      return (RemoveTribunal) super.setAlt(alt);
    }

    @Override
    public RemoveTribunal setFields(java.lang.String fields) {
      return (RemoveTribunal) super.setFields(fields);
    }

    @Override
    public RemoveTribunal setKey(java.lang.String key) {
      return (RemoveTribunal) super.setKey(key);
    }

    @Override
    public RemoveTribunal setOauthToken(java.lang.String oauthToken) {
      return (RemoveTribunal) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveTribunal setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveTribunal) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveTribunal setQuotaUser(java.lang.String quotaUser) {
      return (RemoveTribunal) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveTribunal setUserIp(java.lang.String userIp) {
      return (RemoveTribunal) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveTribunal setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveTribunal set(String parameterName, Object value) {
      return (RemoveTribunal) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateTribunal".
   *
   * This request holds the parameters needed by the the tribunalendpoint server.  After setting any
   * optional parameters, call the {@link UpdateTribunal#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.ctm.eadvogado.tribunalendpoint.model.Tribunal}
   * @return the request
   */
  public UpdateTribunal updateTribunal(com.ctm.eadvogado.tribunalendpoint.model.Tribunal content) throws java.io.IOException {
    UpdateTribunal result = new UpdateTribunal(content);
    initialize(result);
    return result;
  }

  public class UpdateTribunal extends TribunalendpointRequest<com.ctm.eadvogado.tribunalendpoint.model.Tribunal> {

    private static final String REST_PATH = "tribunal";

    /**
     * Create a request for the method "updateTribunal".
     *
     * This request holds the parameters needed by the the tribunalendpoint server.  After setting any
     * optional parameters, call the {@link UpdateTribunal#execute()} method to invoke the remote
     * operation. <p> {@link UpdateTribunal#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.ctm.eadvogado.tribunalendpoint.model.Tribunal}
     * @since 1.13
     */
    protected UpdateTribunal(com.ctm.eadvogado.tribunalendpoint.model.Tribunal content) {
      super(Tribunalendpoint.this, "PUT", REST_PATH, content, com.ctm.eadvogado.tribunalendpoint.model.Tribunal.class);
    }

    @Override
    public UpdateTribunal setAlt(java.lang.String alt) {
      return (UpdateTribunal) super.setAlt(alt);
    }

    @Override
    public UpdateTribunal setFields(java.lang.String fields) {
      return (UpdateTribunal) super.setFields(fields);
    }

    @Override
    public UpdateTribunal setKey(java.lang.String key) {
      return (UpdateTribunal) super.setKey(key);
    }

    @Override
    public UpdateTribunal setOauthToken(java.lang.String oauthToken) {
      return (UpdateTribunal) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateTribunal setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateTribunal) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateTribunal setQuotaUser(java.lang.String quotaUser) {
      return (UpdateTribunal) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateTribunal setUserIp(java.lang.String userIp) {
      return (UpdateTribunal) super.setUserIp(userIp);
    }

    @Override
    public UpdateTribunal set(String parameterName, Object value) {
      return (UpdateTribunal) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Tribunalendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Tribunalendpoint}. */
    @Override
    public Tribunalendpoint build() {
      return new Tribunalendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link TribunalendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setTribunalendpointRequestInitializer(
        TribunalendpointRequestInitializer tribunalendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(tribunalendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
