/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-06-26 16:27:34 UTC)
 * on 2013-07-04 at 08:19:18 UTC 
 * Modify at your own risk.
 */

package com.ctm.eadvogado.processoendpoint.model;

/**
 * Model definition for TipoAssuntoLocal.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class TipoAssuntoLocal extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private TipoAssuntoLocal assuntoLocalPai;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer codigoAssunto;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer codigoPaiNacional;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String descricao;

  /**
   * @return value or {@code null} for none
   */
  public TipoAssuntoLocal getAssuntoLocalPai() {
    return assuntoLocalPai;
  }

  /**
   * @param assuntoLocalPai assuntoLocalPai or {@code null} for none
   */
  public TipoAssuntoLocal setAssuntoLocalPai(TipoAssuntoLocal assuntoLocalPai) {
    this.assuntoLocalPai = assuntoLocalPai;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getCodigoAssunto() {
    return codigoAssunto;
  }

  /**
   * @param codigoAssunto codigoAssunto or {@code null} for none
   */
  public TipoAssuntoLocal setCodigoAssunto(java.lang.Integer codigoAssunto) {
    this.codigoAssunto = codigoAssunto;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getCodigoPaiNacional() {
    return codigoPaiNacional;
  }

  /**
   * @param codigoPaiNacional codigoPaiNacional or {@code null} for none
   */
  public TipoAssuntoLocal setCodigoPaiNacional(java.lang.Integer codigoPaiNacional) {
    this.codigoPaiNacional = codigoPaiNacional;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDescricao() {
    return descricao;
  }

  /**
   * @param descricao descricao or {@code null} for none
   */
  public TipoAssuntoLocal setDescricao(java.lang.String descricao) {
    this.descricao = descricao;
    return this;
  }

  @Override
  public TipoAssuntoLocal set(String fieldName, Object value) {
    return (TipoAssuntoLocal) super.set(fieldName, value);
  }

  @Override
  public TipoAssuntoLocal clone() {
    return (TipoAssuntoLocal) super.clone();
  }

}
