/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-06-26 16:27:34 UTC)
 * on 2013-07-01 at 02:36:04 UTC 
 * Modify at your own risk.
 */

package com.ctm.eadvogado.advogadoendpoint;

/**
 * Service definition for Advogadoendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link AdvogadoendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Advogadoendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.15.0-rc of the  library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://e-advogado.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "advogadoendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Advogadoendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Advogadoendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "autenticarAdvogado".
   *
   * This request holds the parameters needed by the the advogadoendpoint server.  After setting any
   * optional parameters, call the {@link AutenticarAdvogado#execute()} method to invoke the remote
   * operation.
   *
   * @param email
   * @param senha
   * @return the request
   */
  public AutenticarAdvogado autenticarAdvogado(java.lang.String email, java.lang.String senha) throws java.io.IOException {
    AutenticarAdvogado result = new AutenticarAdvogado(email, senha);
    initialize(result);
    return result;
  }

  public class AutenticarAdvogado extends AdvogadoendpointRequest<com.ctm.eadvogado.advogadoendpoint.model.Advogado> {

    private static final String REST_PATH = "autenticarAdvogado/{email}/{senha}";

    /**
     * Create a request for the method "autenticarAdvogado".
     *
     * This request holds the parameters needed by the the advogadoendpoint server.  After setting any
     * optional parameters, call the {@link AutenticarAdvogado#execute()} method to invoke the remote
     * operation. <p> {@link AutenticarAdvogado#initialize(com.google.api.client.googleapis.services.A
     * bstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param email
     * @param senha
     * @since 1.13
     */
    protected AutenticarAdvogado(java.lang.String email, java.lang.String senha) {
      super(Advogadoendpoint.this, "POST", REST_PATH, null, com.ctm.eadvogado.advogadoendpoint.model.Advogado.class);
      this.email = com.google.api.client.util.Preconditions.checkNotNull(email, "Required parameter email must be specified.");
      this.senha = com.google.api.client.util.Preconditions.checkNotNull(senha, "Required parameter senha must be specified.");
    }

    @Override
    public AutenticarAdvogado setAlt(java.lang.String alt) {
      return (AutenticarAdvogado) super.setAlt(alt);
    }

    @Override
    public AutenticarAdvogado setFields(java.lang.String fields) {
      return (AutenticarAdvogado) super.setFields(fields);
    }

    @Override
    public AutenticarAdvogado setKey(java.lang.String key) {
      return (AutenticarAdvogado) super.setKey(key);
    }

    @Override
    public AutenticarAdvogado setOauthToken(java.lang.String oauthToken) {
      return (AutenticarAdvogado) super.setOauthToken(oauthToken);
    }

    @Override
    public AutenticarAdvogado setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (AutenticarAdvogado) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public AutenticarAdvogado setQuotaUser(java.lang.String quotaUser) {
      return (AutenticarAdvogado) super.setQuotaUser(quotaUser);
    }

    @Override
    public AutenticarAdvogado setUserIp(java.lang.String userIp) {
      return (AutenticarAdvogado) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String email;

    /**

     */
    public java.lang.String getEmail() {
      return email;
    }

    public AutenticarAdvogado setEmail(java.lang.String email) {
      this.email = email;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String senha;

    /**

     */
    public java.lang.String getSenha() {
      return senha;
    }

    public AutenticarAdvogado setSenha(java.lang.String senha) {
      this.senha = senha;
      return this;
    }

    @Override
    public AutenticarAdvogado set(String parameterName, Object value) {
      return (AutenticarAdvogado) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getAdvogado".
   *
   * This request holds the parameters needed by the the advogadoendpoint server.  After setting any
   * optional parameters, call the {@link GetAdvogado#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetAdvogado getAdvogado(java.lang.Long id) throws java.io.IOException {
    GetAdvogado result = new GetAdvogado(id);
    initialize(result);
    return result;
  }

  public class GetAdvogado extends AdvogadoendpointRequest<com.ctm.eadvogado.advogadoendpoint.model.Advogado> {

    private static final String REST_PATH = "advogado/{id}";

    /**
     * Create a request for the method "getAdvogado".
     *
     * This request holds the parameters needed by the the advogadoendpoint server.  After setting any
     * optional parameters, call the {@link GetAdvogado#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetAdvogado#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetAdvogado(java.lang.Long id) {
      super(Advogadoendpoint.this, "GET", REST_PATH, null, com.ctm.eadvogado.advogadoendpoint.model.Advogado.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetAdvogado setAlt(java.lang.String alt) {
      return (GetAdvogado) super.setAlt(alt);
    }

    @Override
    public GetAdvogado setFields(java.lang.String fields) {
      return (GetAdvogado) super.setFields(fields);
    }

    @Override
    public GetAdvogado setKey(java.lang.String key) {
      return (GetAdvogado) super.setKey(key);
    }

    @Override
    public GetAdvogado setOauthToken(java.lang.String oauthToken) {
      return (GetAdvogado) super.setOauthToken(oauthToken);
    }

    @Override
    public GetAdvogado setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetAdvogado) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetAdvogado setQuotaUser(java.lang.String quotaUser) {
      return (GetAdvogado) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetAdvogado setUserIp(java.lang.String userIp) {
      return (GetAdvogado) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetAdvogado setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetAdvogado set(String parameterName, Object value) {
      return (GetAdvogado) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertAdvogado".
   *
   * This request holds the parameters needed by the the advogadoendpoint server.  After setting any
   * optional parameters, call the {@link InsertAdvogado#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.ctm.eadvogado.advogadoendpoint.model.Advogado}
   * @return the request
   */
  public InsertAdvogado insertAdvogado(com.ctm.eadvogado.advogadoendpoint.model.Advogado content) throws java.io.IOException {
    InsertAdvogado result = new InsertAdvogado(content);
    initialize(result);
    return result;
  }

  public class InsertAdvogado extends AdvogadoendpointRequest<com.ctm.eadvogado.advogadoendpoint.model.Advogado> {

    private static final String REST_PATH = "advogado";

    /**
     * Create a request for the method "insertAdvogado".
     *
     * This request holds the parameters needed by the the advogadoendpoint server.  After setting any
     * optional parameters, call the {@link InsertAdvogado#execute()} method to invoke the remote
     * operation. <p> {@link InsertAdvogado#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.ctm.eadvogado.advogadoendpoint.model.Advogado}
     * @since 1.13
     */
    protected InsertAdvogado(com.ctm.eadvogado.advogadoendpoint.model.Advogado content) {
      super(Advogadoendpoint.this, "POST", REST_PATH, content, com.ctm.eadvogado.advogadoendpoint.model.Advogado.class);
    }

    @Override
    public InsertAdvogado setAlt(java.lang.String alt) {
      return (InsertAdvogado) super.setAlt(alt);
    }

    @Override
    public InsertAdvogado setFields(java.lang.String fields) {
      return (InsertAdvogado) super.setFields(fields);
    }

    @Override
    public InsertAdvogado setKey(java.lang.String key) {
      return (InsertAdvogado) super.setKey(key);
    }

    @Override
    public InsertAdvogado setOauthToken(java.lang.String oauthToken) {
      return (InsertAdvogado) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertAdvogado setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertAdvogado) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertAdvogado setQuotaUser(java.lang.String quotaUser) {
      return (InsertAdvogado) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertAdvogado setUserIp(java.lang.String userIp) {
      return (InsertAdvogado) super.setUserIp(userIp);
    }

    @Override
    public InsertAdvogado set(String parameterName, Object value) {
      return (InsertAdvogado) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listAdvogado".
   *
   * This request holds the parameters needed by the the advogadoendpoint server.  After setting any
   * optional parameters, call the {@link ListAdvogado#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListAdvogado listAdvogado() throws java.io.IOException {
    ListAdvogado result = new ListAdvogado();
    initialize(result);
    return result;
  }

  public class ListAdvogado extends AdvogadoendpointRequest<com.ctm.eadvogado.advogadoendpoint.model.CollectionResponseAdvogado> {

    private static final String REST_PATH = "advogado";

    /**
     * Create a request for the method "listAdvogado".
     *
     * This request holds the parameters needed by the the advogadoendpoint server.  After setting any
     * optional parameters, call the {@link ListAdvogado#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListAdvogado#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListAdvogado() {
      super(Advogadoendpoint.this, "GET", REST_PATH, null, com.ctm.eadvogado.advogadoendpoint.model.CollectionResponseAdvogado.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListAdvogado setAlt(java.lang.String alt) {
      return (ListAdvogado) super.setAlt(alt);
    }

    @Override
    public ListAdvogado setFields(java.lang.String fields) {
      return (ListAdvogado) super.setFields(fields);
    }

    @Override
    public ListAdvogado setKey(java.lang.String key) {
      return (ListAdvogado) super.setKey(key);
    }

    @Override
    public ListAdvogado setOauthToken(java.lang.String oauthToken) {
      return (ListAdvogado) super.setOauthToken(oauthToken);
    }

    @Override
    public ListAdvogado setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListAdvogado) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListAdvogado setQuotaUser(java.lang.String quotaUser) {
      return (ListAdvogado) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListAdvogado setUserIp(java.lang.String userIp) {
      return (ListAdvogado) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListAdvogado setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListAdvogado setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListAdvogado set(String parameterName, Object value) {
      return (ListAdvogado) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeAdvogado".
   *
   * This request holds the parameters needed by the the advogadoendpoint server.  After setting any
   * optional parameters, call the {@link RemoveAdvogado#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveAdvogado removeAdvogado(java.lang.Long id) throws java.io.IOException {
    RemoveAdvogado result = new RemoveAdvogado(id);
    initialize(result);
    return result;
  }

  public class RemoveAdvogado extends AdvogadoendpointRequest<com.ctm.eadvogado.advogadoendpoint.model.Advogado> {

    private static final String REST_PATH = "advogado/{id}";

    /**
     * Create a request for the method "removeAdvogado".
     *
     * This request holds the parameters needed by the the advogadoendpoint server.  After setting any
     * optional parameters, call the {@link RemoveAdvogado#execute()} method to invoke the remote
     * operation. <p> {@link RemoveAdvogado#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveAdvogado(java.lang.Long id) {
      super(Advogadoendpoint.this, "DELETE", REST_PATH, null, com.ctm.eadvogado.advogadoendpoint.model.Advogado.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveAdvogado setAlt(java.lang.String alt) {
      return (RemoveAdvogado) super.setAlt(alt);
    }

    @Override
    public RemoveAdvogado setFields(java.lang.String fields) {
      return (RemoveAdvogado) super.setFields(fields);
    }

    @Override
    public RemoveAdvogado setKey(java.lang.String key) {
      return (RemoveAdvogado) super.setKey(key);
    }

    @Override
    public RemoveAdvogado setOauthToken(java.lang.String oauthToken) {
      return (RemoveAdvogado) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveAdvogado setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveAdvogado) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveAdvogado setQuotaUser(java.lang.String quotaUser) {
      return (RemoveAdvogado) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveAdvogado setUserIp(java.lang.String userIp) {
      return (RemoveAdvogado) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveAdvogado setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveAdvogado set(String parameterName, Object value) {
      return (RemoveAdvogado) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateAdvogado".
   *
   * This request holds the parameters needed by the the advogadoendpoint server.  After setting any
   * optional parameters, call the {@link UpdateAdvogado#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.ctm.eadvogado.advogadoendpoint.model.Advogado}
   * @return the request
   */
  public UpdateAdvogado updateAdvogado(com.ctm.eadvogado.advogadoendpoint.model.Advogado content) throws java.io.IOException {
    UpdateAdvogado result = new UpdateAdvogado(content);
    initialize(result);
    return result;
  }

  public class UpdateAdvogado extends AdvogadoendpointRequest<com.ctm.eadvogado.advogadoendpoint.model.Advogado> {

    private static final String REST_PATH = "advogado";

    /**
     * Create a request for the method "updateAdvogado".
     *
     * This request holds the parameters needed by the the advogadoendpoint server.  After setting any
     * optional parameters, call the {@link UpdateAdvogado#execute()} method to invoke the remote
     * operation. <p> {@link UpdateAdvogado#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.ctm.eadvogado.advogadoendpoint.model.Advogado}
     * @since 1.13
     */
    protected UpdateAdvogado(com.ctm.eadvogado.advogadoendpoint.model.Advogado content) {
      super(Advogadoendpoint.this, "PUT", REST_PATH, content, com.ctm.eadvogado.advogadoendpoint.model.Advogado.class);
    }

    @Override
    public UpdateAdvogado setAlt(java.lang.String alt) {
      return (UpdateAdvogado) super.setAlt(alt);
    }

    @Override
    public UpdateAdvogado setFields(java.lang.String fields) {
      return (UpdateAdvogado) super.setFields(fields);
    }

    @Override
    public UpdateAdvogado setKey(java.lang.String key) {
      return (UpdateAdvogado) super.setKey(key);
    }

    @Override
    public UpdateAdvogado setOauthToken(java.lang.String oauthToken) {
      return (UpdateAdvogado) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateAdvogado setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateAdvogado) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateAdvogado setQuotaUser(java.lang.String quotaUser) {
      return (UpdateAdvogado) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateAdvogado setUserIp(java.lang.String userIp) {
      return (UpdateAdvogado) super.setUserIp(userIp);
    }

    @Override
    public UpdateAdvogado set(String parameterName, Object value) {
      return (UpdateAdvogado) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Advogadoendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Advogadoendpoint}. */
    @Override
    public Advogadoendpoint build() {
      return new Advogadoendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link AdvogadoendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setAdvogadoendpointRequestInitializer(
        AdvogadoendpointRequestInitializer advogadoendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(advogadoendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
